CREATE TABLE perfis
(
    id                      BIGINT PRIMARY KEY AUTO_INCREMENT,
    nome                    VARCHAR(255) NOT NULL,
    cadastrar_funcionario   BOOLEAN      NOT NULL,
    ler_funcionario         BOOLEAN      NOT NULL,
    atualizar_funcionario   BOOLEAN      NOT NULL,
    deletar_funcionario     BOOLEAN      NOT NULL,
    listar_funcionario      BOOLEAN      NOT NULL,
    cadastrar_paciente      BOOLEAN      NOT NULL,
    ler_paciente            BOOLEAN      NOT NULL,
    atualizar_paciente      BOOLEAN      NOT NULL,
    deletar_paciente        BOOLEAN      NOT NULL,
    listar_paciente         BOOLEAN      NOT NULL,
    cadastrar_formulario    BOOLEAN      NOT NULL,
    ler_formulario          BOOLEAN      NOT NULL,
    atualizar_formulario    BOOLEAN      NOT NULL,
    deletar_formulario      BOOLEAN      NOT NULL,
    listar_formulario       BOOLEAN      NOT NULL,
    cadastrar_especialidade BOOLEAN      NOT NULL,
    ler_especialidade       BOOLEAN      NOT NULL,
    atualizar_especialidade BOOLEAN      NOT NULL,
    deletar_especialidade   BOOLEAN      NOT NULL,
    listar_especialidade    BOOLEAN      NOT NULL,
    cadastrar_convenio      BOOLEAN      NOT NULL,
    ler_convenio            BOOLEAN      NOT NULL,
    atualizar_convenio      BOOLEAN      NOT NULL,
    deletar_convenio        BOOLEAN      NOT NULL,
    listar_convenio         BOOLEAN      NOT NULL
);